config/routes.rb
Rails.application.routes.draw do
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'gifting#landing'

  get '/baytallies', to: 'baytallies#index'
  
  get '/choosebay', to: 'booking#choosebay'
  get '/enterdetails', to: 'booking#enterdetails'
  get '/bookingconfirmation', to: 'booking#bookingconfirmation'

  get '/landing', to: 'gifting#landing'
  post '/profile', to: 'gifting#profile'
  post '/bookingconfirmation', to: 'booking#bookingconfirmation'
  get '/profile', to: 'gifting#profile'
  get '/login', to: 'gifting#login'
  post '/log_user_in', to: 'gifting#log_user_in'
  post '/checkdetails', to: 'booking#checkdetails'
  get '/button1', to: 'booking#button1'
  get '/button2', to: 'booking#button2'
  get '/button3', to: 'booking#button3'
  get '/item1', to: 'gifting#item1'
  get '/item2', to: 'gifting#item2'



  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baytally.rb
class Baytally < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/baytallies_controller.rb
class BaytalliesController < ApplicationController
	def index
		@baytallies = Baytally.all
	end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
	require 'net/smtp'

	# populates the bays with available spots
	def choosebay
		@bay1 = User.where(date: Date.today, bay: 1).count
		@bay2 = User.where(date: Date.today, bay: 2).count
		@bay3 = User.where(date: Date.today, bay: 3).count
	end

	# records which bay was selected
	def button1
		if User.where(date: Date.today, bay: 1).count == 0
			session[:baychosen] = 0
		else
			session[:baychosen] = 1
		end
		redirect_to '/enterdetails'
	end

	def button2
		if User.where(date: Date.today, bay: 2).count == 0
			session[:baychosen] = 0
		else
			session[:baychosen] = 2
		end
		redirect_to '/enterdetails'
	end

	def button3
		if User.where(date: Date.today, bay: 3).count == 0
			session[:baychosen] = 0
		else
			session[:baychosen] = 3
		end
		redirect_to '/enterdetails'
	end

	def enterdetails
	end

	# handles verification on /enterdetails 
	def checkdetails
		#  TO DO: add a hash function in the line below and then have 
		#  another hash column in Person model that is a hash of the password column
		@temp = Person.find_by(email: params[:email], password: params[:password])

		if @temp == nil then
			@error = "Your email or password is incorrect."
			render 'enterdetails'
		elsif session[:baychosen] == 0 then
			@error = "This bay is full."
			render 'enterdetails'
		else
		    # TO DO: shoot email to @temp.email with @baycode and @parkingcode
		    # @parkingcode = rand(32**8).to_s(32)
		    # @baycode = session[:baychosen]
		    # @temp.parking_code = @parkingcode
		    # @temp.baycode = @baycode
		    # FirstMailer.sample_email(@temp).deliver
		    redirect_to '/bookingconfirmation'
		end
	end



	def bookingconfirmation
	end
end

app/controllers/gifting_controller.rb
class GiftingController < ApplicationController
	

	# resets session values to false
	def landing
		session[:increase] = false
		session[:redeemed] = false
	end

	def login
	end

	# deals with verification/ consequences of /login form and stores the user to prevent multiple same-day logins
	def log_user_in
		session[:increase] = false
		session[:redeemed] = false
		# TO DO: add a hash function in the line below and then have 
		# another hash column in Person model that is a hash of the password column
		@temp = Person.find_by(email: params[:email], password: params[:password])
		if @temp == nil or !@temp.has_space then
			@error = "Your email or password is incorrect."
			render 'login'
		else
			@user = User.new
			@user.email = @temp.email
			@user.password = @temp.password
			@user.bay = @temp.bay
			@user.date = Date.today
        	if User.find_by(email: @user.email, date: @user.date) == nil then
		 	  @user.save
		 	  @temp.points += 20
		      @temp.save
		      session[:increase] = true
		    end

		    session[:email] = @temp.email
			redirect_to '/profile'
		end
	end

	# handles /profile 
	def profile
		@temp = Person.find_by(email: session[:email])
		@current = @temp
	end

	# handle user redeeming smoothie voucher
	def item1
		@person = Person.find_by(email: session[:email])
		@person.points -= 50
		@person.save
		@vouchercode = rand(32**8).to_s(32)
		session[:redeemed] = true
		# TO DO: send email to @person.email with voucher number and item name (smoothie)
		# @parkingcode = rand(32**8).to_s(32)
		# @baycode = session[:baychosen]
		# @temp.parking_code = @parkingcode
		# @temp.baycode = @baycode
		# FirstMailer.sample_email(@person).deliver
		redirect_to '/profile'
	end

	# handle user redeeming takealot voucher
	def item2
		@person = Person.find_by(email: session[:email])
		@person.points -= 250
		@person.save
		@vouchercode = rand(32**8).to_s(32)
		session[:redeemed] = true
		# TO DO: send email to @person.email with voucher number and item name (takealot)
		# shoot email to @temp.email with @baycode and @parkingcode
		# @parkingcode = rand(32**8).to_s(32)
		# @baycode = session[:baychosen]
		# @temp.parking_code = @parkingcode
		# @temp.baycode = @baycode
		# FirstMailer.sample_email(@person).deliver
		redirect_to '/profile'
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:email, :password, :has_space, :points, :bay)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end
	def create
	end
	def edit
	end
	def show
	end
	def update
	end
	def destroy
	end
	def new
	end
	private
	  def user_params
		  params.require(:user).permit(:email, :password)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baytallies_helper.rb
module BaytalliesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/baytallies/index.html.erb
<h1>Bay Tallies</h1>

<table>
  <thead>
    <tr>
      <th>Bay 1</th>
      <th>Bay 2</th>
      <th>Bay 3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<tr>
    <% @baytallies.each do |baytally| %>
        <td><b><%= baytally.tally %></b> Open Spaces </td>
    <% end %>
    </tr>
  </tbody>
</table>

app/views/booking/bookingconfirmation.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 align="center"> You have reserved a parking space! </h1>

<p align="center"> A confirmation email will be sent to your email. Present it to the parking guard when entering the bay.  </p><br>

<div align="center">
	<a class="btn btn-primary btn-lg" href="/landing">Home</a>
</div>

app/views/booking/choosebay.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<h1 align="center"> Choose your parking bay </h1>
<div>
	<br>
	<a style="max-width: 400px; margin: auto;" class="btn btn-primary btn-lg btn-block" href="/button1"><%= "Underground (#{@bay1} Available)" %> </a> <br>
	<br>
	<a style="max-width: 400px; margin: auto;" class="btn btn-primary btn-lg btn-block" href="/button2"><%= "L-Bay (#{@bay2} Available)" %> </a><br>
	<br>
	<a style="max-width: 400px; margin: auto;" class="btn btn-primary btn-lg btn-block" href="/button3"><%= "N-Bay (#{@bay3} Available)" %> </a><br>
	<br>
	<br>
</div>
<div align="center">
	<a class="btn btn-secondary btn-lg" href="/landing">Back</a>
</div>

app/views/booking/enterdetails.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 align="center"> Please enter your details: </h1>
 	 <br>
 <p align="center" style="color:red"> <%= @error %> </p>

<div align="center">
 <%= form_tag '/checkdetails' do %>
	<div class="field">
		<%= text_field_tag :email, nil, placeholder: "Email Address"%>
	</div>
	<div class="field">
		<br>
		<%= text_field_tag :password, nil, placeholder: "Password"%>
	</div><br>
	<div>
		<br>
		<a class="btn btn-secondary btn-lg" href="/choosebay">Cancel</a> &ensp;
		<%= submit_tag "Reserve Space", class: "btn btn-primary btn-lg" %>
	</div>
<% end %>
</div>
<br>

app/views/gifting/landing.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 align="center"> Welcome to GetSmarter's Parking App </h1>

<div>
	<br>
	<a style="max-width: 400px; margin: auto;" class="btn btn-primary btn-lg btn-block" href="/login"><%= "Offer Your Parking Space" %> </a> <br>
	<br>
	<a style="max-width: 400px; margin: auto;" class="btn btn-primary btn-lg btn-block" href="/choosebay"><%= "Book Your Parking Space" %> </a><br>
	<br>
	<br>
	<div align="center">
		<a class="btn btn-info btn-lg" href="/profile">Profile</a>
	</div>
</div>

app/views/gifting/login.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 align="center"> Log In </h1><br>
<p align="center" style="color:red"> <%= @error %> </p>
<div align="center">
 <%= form_tag '/log_user_in' do %>
	<div class="field">
		<%= text_field_tag :email, nil, placeholder: "Email Address" %>
	</div>
	<div class="field">
		<br>
		<%= text_field_tag :password, nil, placeholder: "Password" %>
	</div><br><br>
	<div>
		<a class="btn btn-secondary btn-lg" href="/landing">Cancel</a> &ensp;
		<%= submit_tag "Offer Space", class: "btn btn-primary btn-lg" %>
	</div>
<% end %>
</div>
<br>

app/views/gifting/profile.html.erb
<br>
<br>
<br>
<br>


<br>
<h1 align="center"> Redeem Your Rewards </h3>
<% if session[:increase] %>
<div class="alert alert-success" role="alert" align="center">
  Congrats! You've earned 20 Reward Points!
</div>
<% end %>
<% if session[:redeemed] %>
<div class="alert alert-success" role="alert" align="center">
  Your item has been redeemed! Instructions have been emailed to you.
</div>
<% end %>
<h4 align="center"> You Have <strong><%= @current.points %></strong> Reward Points</h4>
<br>


<div style="max-width: 600px; margin: auto;" class="card-deck">
  <div class="card" data-toggle="modal" data-target=
  <% if @current.points >= 50 %>
  "#check1"
  <% else %>
  "#insufficient"
  <% end %>
    >
    <img class="card-img-top" src="/assets/smoothie.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title text-center">Free Smoothie</h5>
      <p class="card-text text-right">50 Reward Points</p>
    </div>
  </div>
  <div class="card" data-toggle="modal" data-target=
  <% if @current.points >= 250 %>
  "#check2"
  <% else %>
  "#insufficient"
  <% end %>
    >
    <img class="card-img-top" src="/assets/takealot.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title text-center">R200 Takealot Voucher</h5>
      <p class="card-text text-right">250 Reward Points</p>
    </div>
  </div>
</div>
<br>
<br>
<h3 align="center"> You're signed in as:  <%= @current.email %> </h1><br>

<div align="center">
	<a class="btn btn-info btn-lg" href="/landing">Home</a>
</div>

<!-- confirmation modal item 1 -->
<div class="modal fade" id="check1" tabindex="-1" role="dialog" aria-labelledby="check1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="check1">Confirm Purchase</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you would like to redeem a smoothie?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a class="btn btn-primary" href="/item1" >Redeem Item</a>
      </div>
    </div>
  </div>
</div>


<!-- confirmation modal item 2 -->
<div class="modal fade" id="check2" tabindex="-1" role="dialog" aria-labelledby="check2" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="check2">Confirm Purchase</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you would like to redeem a takealot voucher?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a class="btn btn-primary" href="/item2" >Redeem Item</a>
      </div>
    </div>
  </div>
</div>

<!-- insufficient points modal -->
<div class="modal fade" id="insufficient" tabindex="-1" role="dialog" aria-labelledby="insufficient" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="insufficient">Sorry!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You have insufficent reward points.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- success modal -->
<div class="modal fade" id="success" tabindex="-1" role="dialog" aria-labelledby="success" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="success">Item Redeemed!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        A confirmation email has been sent to you with your voucher code.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :has_space %>
    <%= form.check_box :has_space %>
  </div>

  <div class="field">
    <%= form.label :bay %>
    <%= form.number_field :bay %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Employees</h1>

<table align="center">
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Has Space&ensp;</th>
      <th>Bay&ensp;</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td ><%= person.email %>&ensp;</td>
        <td><%= person.password %></td>
        <td align="center"><%= person.has_space %>&ensp;</td>
        <td align="center"><%= person.bay %>&ensp;</td>
        <td align="center"><%= person.points %>&ensp;</td>
        <td>&ensp;<%= link_to 'Show', person%> &ensp;</td>
        <td><%= link_to 'Edit', edit_person_path(person) %>&ensp;</td> 
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a style="max-width: 400px; margin: auto;" class="btn btn-primary btn-lg btn-block" href= "people/new" ><%= "New Person" %> </a> <br>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @person.password %>
</p>

<p>
  <strong>Has space:</strong>
  <%= @person.has_space %>
</p>

<p>
  <strong>Bay:</strong>
  <%= @person.bay %>
</p>

<p>
  <strong>Points:</strong>
  <%= @person.points %>
</p>



<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/users/new.html.erb
<br>
<h1> Login to offer your space and receive rewards: </h1>
<!-- 
<%= form_for @current do |form| %>
	<div class="field">
		<%= form.label :email %>
		<%= form.text_field :email %>
	</div>
	<div class="field">
		<%= form.label :password %>
		<%= form.text_field :password %>
	</div>
	<div>
		<%= form.submit "Offer Space" %>
	</div>
<% end %>
 -->

 <%= form_tag '/profile' do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email %>
	</div>
	<div class="field">
		<%= label_tag :password %>
		<%= text_field_tag :password %>
	</div>
	<div>
		<%= submit_tag "Offer Space" %>
	</div>
<% end %>

<br>
<%= link_to "Cancel", '/landing' %>